version: "3.1"
services:

  webserver:
    image: nginx:alpine
    container_name: design-pattern-webserver
    working_dir: /application
    volumes:
        - ./src:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: design-pattern-php-fpm
    working_dir: /application
    volumes:
      - ./src:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    depends_on: 
      - webserver

